# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Daniel Barbosa
    url: '#about'
    weight: 10
  - name: Research
    url: '#research'
    weight: 20
  - name: Working Papers
    url: '#working_papers'
    parent: 'Research'
    weight: 2
  # - name: Projects
  #   url: '#projects'
  #   parent: 'Research'
  #   weight: 3
  - name: Teaching
    url: '#teaching'
    weight: 30
  - name: Others
    url: ''
    weight: 40
    identifier: others
  - name: Software
    url: 'software'
    weight: 1
    parent: 'others'
  - name: Data
    url: 'data_section'
    weight: 2
    parent: 'others'
  # - name: Blog
  #   url: '#posts'
  #   weight: 3
  # parent: 'others'
  - name: Contact
    url: '#contact'
    weight: 50
  - name: CV
    url: uploads/cv_daniel_ac_barbosa.pdf
    weight: 60
